### PR TITLE
Build from source

### PR DESCRIPTION
**Pull request by Mailaender**
Closes https://github.com/flathub/net.worldofpadman.WoP/issues/2

### CODE REVIEW

**Comment by hfiguiere** [comment]
seems like it want to run a binary on the wrong arch:

```
tools/linux/glslangValidator: tools/linux/glslangValidator: cannot execute binary file
```

**Comment by hfiguiere** [comment]
That's probably https://github.com/PadWorld-Entertainment/worldofpadman/pull/181/files

**Comment by AsciiWolf** [comment]
Do network support work? See [this comment](https://github.com/flathub/flathub/pull/3754#issuecomment-1366604128). Also, the ingame videos were choppy, when using the source build. And there were some other issues.

**Comment by Mailaender** [comment]
I only tested it locally. The intro video played just fine.

**Comment by AsciiWolf** [comment]
What about the network support? That was the main issue I was not able to fix.

It could be a similar problem to https://github.com/flathub/net.cubers.assault.AssaultCube/commit/aed7f5dee3ca9875c94f872c8761b2a8cbb21711.

**Comment by Mailaender** [comment]
I think this may not be the problem in here: https://github.com/PadWorld-Entertainment/worldofpadman/commit/523c835eb0738d0da22b0e078a587108e8c10e30

**Comment by AsciiWolf** [comment]
Good catch! :-)

**Comment by Mailaender** [comment]
I can join and play network games just fine.

**Comment by AsciiWolf** [comment]
Nice! I have just tried the [test build](https://github.com/flathub/net.worldofpadman.WoP/pull/7#issuecomment-1676395279) and it looks like that everything works fine now. :-)

**Comment by Mailaender** [comment]
I just disabled the Vulkan renderer as suggested in https://github.com/PadWorld-Entertainment/worldofpadman/pull/181#issuecomment-1677895041 to fix the build on ARM.

**Comment by AsciiWolf** [comment]
> Build [58789 successful](https://buildbot.flathub.org/#/builders/6/builds/58789) To test this build, install it from the testing repository

Works fine. :-)

**Comment by AsciiWolf** [comment]
Should I merge this PR or is there anything else you would like to add first?

**Comment by Mailaender** [comment]
I am happy now as well.

**Pull request merged**
